# Generated by Django 3.1.12 on 2021-09-07 14:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InvalidationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_requested", models.DateTimeField(verbose_name="Date requested")),
                ("urls", models.TextField(verbose_name="Urls")),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested by",
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(to="wagtailcore.Site", verbose_name="Sites"),
                ),
            ],
            options={
                "verbose_name": "Invalidation request",
                "verbose_name_plural": "Invalidation requests",
                "ordering": ["-date_requested"],
            },
        ),
    ]
