# Generated by Django 3.2.12 on 2022-08-19 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        ("wagtailcacheinvalidator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CacheSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purge_all",
                    models.BooleanField(
                        default=False,
                        help_text="Purge all cache for this site when pages are (un)published",
                        verbose_name="purge all",
                    ),
                ),
                (
                    "cloudfront_enabled",
                    models.BooleanField(default=False, verbose_name="enabled"),
                ),
                (
                    "cloudfront_distribution_id",
                    models.CharField(max_length=255, verbose_name="distribution ID"),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache",
                "verbose_name_plural": "Cache",
            },
        ),
    ]
