# Generated by Django 4.1.3 on 2022-11-25 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("wagtailcacheinvalidator", "0002_cachesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurgeCacheSite",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("wagtailcore.site",),
        ),
    ]
