# Generated by Django 5.2.4 on 2025-07-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcacheinvalidator", "0003_purgecachesite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachesettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
